### PR TITLE
resource/alicloud_db_instance: Fix tde_status cannot be displayed

### PR DESCRIPTION
**Pull request by zwc01090043**

### CODE REVIEW

**Review by MrWolong — COMMENTED** [review]
approved

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Comment by zwc01090043** [comment]
image

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Review by MrWolong — COMMENTED** [review]
approved

**Comment by zwc01090043** [comment]
image

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Pull request merged**
