### PR TITLE
Unable to delete expired object marker on versioned bucket in lifecycle rule

### PR DESCRIPTION
**Pull request by kapilkumartrivedi**
On versioned bucket (versioning-enabled or versioning-suspended bucket), one can add this element in the lifecycle configuration to direct OSS to delete expired object delete markers.

### CODE REVIEW

**Comment by kapilkumartrivedi** [comment]
@xiaozhu36 is there anything else that we would need ? can we merge ?

**Comment by gitarun786** [comment]
> @xiaozhu36 is there anything else that we would need ? can we merge ?

@xiaozhu36 ,are we good to merge these updates ? We are waiting for this feature .

**Comment by gitarun786** [comment]
@xiaozhu36 ,are we good to merge these updates ? We are waiting for this feature.

**Comment by huiguangjun** [comment]
merge to this pr
#3441

**Comment by kapilkumartrivedi** [comment]
@huiguangjun  i think #3441 is already merged. what should i do?

**Pull request closed without merging**
