### PR TITLE
resource/alicloud_amqp_instance: fix bug while creating instance use a domestic account in ap-southeast-1.

### PR DESCRIPTION
**Pull request by ChenHanZhang**

### CODE REVIEW

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Comment by ChenHanZhang** [comment]
国际站测试：

**Comment by ChenHanZhang** [comment]
国际站测试：

**Comment by ChenHanZhang** [comment]
国际站测试=== RUN   TestAccAliCloudAmqpInstance_professional
--- PASS: TestAccAliCloudAmqpInstance_professional (458.16s)
=== RUN   TestAccAliCloudAmqpInstance_enterprise
--- PASS: TestAccAliCloudAmqpInstance_enterprise (509.94s)
=== RUN   TestAccAliCloudAmqpInstance_vip
    provider_test.go:310: Skipping the test case when not in specified days []int{1} of every month
--- SKIP: TestAccAliCloudAmqpInstance_vip (0.00s)
=== RUN   TestAccAliCloudAmqpInstance_basic6128
--- PASS: TestAccAliCloudAmqpInstance_basic6128 (139.40s)
=== RUN   TestAccAliCloudAmqpInstance_ApSouthEast
    provider_test.go:143: Skipping unsupported region eu-central-1. Supported regions: [ap-southeast-1]. Using ap-southeast-1 as this test region
--- PASS: TestAccAliCloudAmqpInstance_ApSouthEast (135.55s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  1246.840s

**Review by xiaozhu36 — APPROVED** [review]

**Comment by ChenHanZhang** [comment]
国内站
=== RUN   TestAccAliCloudAmqpInstance_professional
--- PASS: TestAccAliCloudAmqpInstance_professional (448.96s)
=== RUN   TestAccAliCloudAmqpInstance_enterprise
--- PASS: TestAccAliCloudAmqpInstance_enterprise (497.90s)
=== RUN   TestAccAliCloudAmqpInstance_vip
    provider_test.go:310: Skipping the test case when not in specified days []int{1} of every month
--- SKIP: TestAccAliCloudAmqpInstance_vip (0.00s)
=== RUN   TestAccAliCloudAmqpInstance_basic6128
--- PASS: TestAccAliCloudAmqpInstance_basic6128 (137.88s)
=== RUN   TestAccAliCloudAmqpInstance_ApSouthEast
    provider_test.go:143: Skipping unsupported region eu-central-1. Supported regions: [ap-southeast-1]. Using ap-southeast-1 as this test region
--- PASS: TestAccAliCloudAmqpInstance_ApSouthEast (132.00s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  1220.739s

**Comment by ChenHanZhang** [comment]
国际站：
=== RUN   TestAccAliCloudAmqpInstance_professional
--- PASS: TestAccAliCloudAmqpInstance_professional (458.41s)
=== RUN   TestAccAliCloudAmqpInstance_enterprise
--- PASS: TestAccAliCloudAmqpInstance_enterprise (507.29s)
=== RUN   TestAccAliCloudAmqpInstance_vip
    provider_test.go:310: Skipping the test case when not in specified days []int{1} of every month
--- SKIP: TestAccAliCloudAmqpInstance_vip (0.00s)
=== RUN   TestAccAliCloudAmqpInstance_basic6128
--- PASS: TestAccAliCloudAmqpInstance_basic6128 (140.10s)
=== RUN   TestAccAliCloudAmqpInstance_ApSouthEast
    provider_test.go:143: Skipping unsupported region eu-central-1. Supported regions: [ap-southeast-1]. Using ap-southeast-1 as this test region
--- PASS: TestAccAliCloudAmqpInstance_ApSouthEast (134.51s)
PASS
ok      github.com/aliyun/terraform-provider-alicloud/alicloud  1244.101s

**Pull request merged**
