### PR TITLE
 alicloud_alikafka_instance_allowed_ip_attachment: support internet in allowed_type

### PR DESCRIPTION
**Pull request by cofyc**
image
See API docs: https://next.api.aliyun.com/document/alikafka/2019-09-16/UpdateAllowedIp

### CODE REVIEW

**Comment by cofyc** [comment]
cc @xiaozhu36 

terraform provider 有办法根据 API Specs 来生成吗？然后微调一些易用性的地方。这些小的细节持续维护，感觉成本很高。阿里云 API 也会越来越多。

**Comment by gmi-vishal** [comment]
@CLAassistant @cofyc @xiaozhu36 Can you merge this change plzzz

**Comment by gmi-vishal** [comment]
@jameslcj @xiaozhu36 @lxwzy Can anyone of you please review this and merge this PR,
I am waiting for this feature since long time !!

**Review by gmi-vishal — APPROVED** [review]

**Comment by gmi-vishal** [comment]
@xiaozhu36 can you please look at this PR ??

**Comment by gmi-vishal** [comment]
This PR can be closed as its fixed as per 
https://github.com/aliyun/terraform-provider-alicloud/pull/5235

**Pull request closed without merging**
