### PR TITLE
ADB MySQL output output connection string after creation

### PR DESCRIPTION
**Pull request by jokerhenson**
图片

### CODE REVIEW

**Comment by foo-source** [comment]
@xiaozhu36 , there is still no connection_string instance is created. 
Output:
```
adb_instance = [
  {
    "db_cluster_category" = "Cluster"
    "db_cluster_version" = "3.0"
    "db_node_class" = "C8"
    "db_node_count" = 2
    "db_node_storage" = 100
    "description" = "adb-mysql"
    "id" = "am-3ns3e192fjrobx0i2"
    "maintain_time" = "22:00Z-23:00Z"
    "pay_type" = "PostPaid"
    "security_ips" = [
      "",
    ]
    "timeouts" = {
      "create" = "60m"
    }
    "vswitch_id" = "vsw-"
    "zone_id" = "cn-hongkong-b"
  },
]
```

**Comment by jokerhenson** [comment]
> @xiaozhu36 , there is still no connection_string after the instance is created.
> Output:
> 
> ```
> adb_instance = [
>   {
>     "db_cluster_category" = "Cluster"
>     "db_cluster_version" = "3.0"
>     "db_node_class" = "C8"
>     "db_node_count" = 2
>     "db_node_storage" = 100
>     "description" = "adb-mysql"
>     "id" = "am-3ns3e192fjrobx0i2"
>     "maintain_time" = "22:00Z-23:00Z"
>     "pay_type" = "PostPaid"
>     "security_ips" = [
>       "",
>     ]
>     "timeouts" = {
>       "create" = "60m"
>     }
>     "vswitch_id" = "vsw-"
>     "zone_id" = "cn-hongkong-b"
>   },
> ]
> ```

Are you using version 1.92.0 or earlier ? It is added in 1.93.0.

**Comment by foo-source** [comment]
@xiaozhu36 , thanks for your reply. I just notice got this message when `terraform init`.
```
Warning: registry.terraform.io: For users on Terraform 0.13 or greater, this provider has moved to aliyun/alicloud. Please update your source in required_providers.
```

**Comment by foo-source** [comment]
@xiaozhu36 , I am not able to install latest version. It kept install v1.92.0.
```
Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/alicloud versions matching "~> 1.0, ~> 1.0"...
- Installing hashicorp/alicloud v1.92.0...
- Installed hashicorp/alicloud v1.92.0 (signed by HashiCorp)


Warning: Additional provider information from registry

The remote registry returned warnings for
registry.terraform.io/hashicorp/alicloud:
- For users on Terraform 0.13 or greater, this provider has moved to
aliyun/alicloud. Please update your source in required_providers.
```

**Comment by jokerhenson** [comment]
> @jokerhenson , I am not able to install latest version. It kept install v1.92.0. Terraform version: `Terraform v0.13.0`.
> I notice the version still `1.92.0`: https://registry.terraform.io/providers/hashicorp/alicloud/latest
> 
> ```
> Initializing the backend...
> 
> Initializing provider plugins...
> - Finding hashicorp/alicloud versions matching "~> 1.0, ~> 1.0"...
> - Installing hashicorp/alicloud v1.92.0...
> - Installed hashicorp/alicloud v1.92.0 (signed by HashiCorp)
> 
> 
> Warning: Additional provider information from registry
> 
> The remote registry returned warnings for
> registry.terraform.io/hashicorp/alicloud:
> - For users on Terraform 0.13 or greater, this provider has moved to
> aliyun/alicloud. Please update your source in required_providers.
> ```

Sorry, 1.93.0 has been released, but can’t be updated automatically, have already contacted the community to check. Could try install 1.93.0 manually, https://github.com/aliyun/terraform-provider-alicloud/releases/tag/v1.93.0.

**Comment by foo-source** [comment]
@jokerhenson , noted with thanks.

**Pull request merged**
