### PR TITLE
resource/alicloud_cs_serverless_kubernetes: support modify cluster name and migrate cluster; add params custom_san, addon version and add param delete_options for delete operation; update vpc_id as Optional; deprecate load_balancer_spec, logging_type, sls_project_name; remove force_update, create_v2_cluster, vswitch_id. resource/alicloud_cs_managed_kubernetes: support update custom_san, refactor modifyCluster and output error message if deleteCluster fails. resource/alicloud_cs_kubernetes: refactor modifyCluster and output error message if deleteCluster fails. docs: improve code sample for alicloud_cs_kubernetes, alicloud_cs_serverless_kubernetes.

### PR DESCRIPTION
**Pull request by sanyangji**

### CODE REVIEW

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Review by ChenHanZhang — COMMENTED** [review]
approved

**Comment by sanyangji** [comment]
Test records:
------@task-begin---------- 
Running tests: TestAccAliCloudCSKubernetes_basic|TestAccAliCloudCSKubernetes_prepaid|TestAccAliCloudCSManagedKubernetes_basic|TestAccAliCloudCSManagedKubernetes_essd_migrate_upgrade|TestAccAliCloudCSManagedKubernetes_controlPlanLog|TestAccAliCloudCSServerlessKubernetes_basic|TestAccAliCloudCSServerlessKubernetesAuto
=== RUN   TestAccAliCloudCSKubernetes_basic
--- PASS: TestAccAliCloudCSKubernetes_basic (4278.76s)
=== RUN   TestAccAliCloudCSKubernetes_prepaid
--- PASS: TestAccAliCloudCSKubernetes_prepaid (1119.93s)
=== RUN   TestAccAliCloudCSManagedKubernetes_basic
--- PASS: TestAccAliCloudCSManagedKubernetes_basic (1031.39s)
=== RUN   TestAccAliCloudCSManagedKubernetes_essd_migrate_upgrade
--- PASS: TestAccAliCloudCSManagedKubernetes_essd_migrate_upgrade (1604.10s)
=== RUN   TestAccAliCloudCSManagedKubernetes_controlPlanLog
--- PASS: TestAccAliCloudCSManagedKubernetes_controlPlanLog (810.14s)
=== RUN   TestAccAliCloudCSServerlessKubernetes_basic
--- PASS: TestAccAliCloudCSServerlessKubernetes_basic (1442.48s)
=== RUN   TestAccAliCloudCSServerlessKubernetesAuto
--- PASS: TestAccAliCloudCSServerlessKubernetesAuto (954.08s)
PASS
ok  	github.com/aliyun/terraform-provider-alicloud/alicloud	11241.519s
------@task-end----------

**Pull request merged**
